<?php require_once "templates/header.phtml" ?>

        <article>
            <h3>Alumno de TUDAI</h3>
            <h4>WEB II</h4>
            <ul>
                <li>Trabajo Práctico Especial</li>
                <li>Segunda Entrega</li>
            </ul>
            <h4>Tema</h4>
            <ul>
                <li>GYM</li>
                <li>Sistema de Alumnos y Rutinas de Ejercicios</li>
            </ul>
            <h4>Grupo N°: 111</h4>
            <ul>
                <li>Nombre: Garay Alejandro</li>
                <li>DNI: 18.038.228 </li>
            </ul>
        </article>
        <aside>
            <h3>UNICEN</h3>
            <ul>
                <li>Facultad de Ciencias Exactas</li>
            <figure>
                <img src="images/exa.jpeg" alt="Foto del logo de Exactas">
            </figure>
        </aside>

<?php require_once "templates/footer.phtml" ?> 