
    </main>
    <footer>
        <br>
        <h5>Si desea contactarnos comuniquese al 2494-640291 (nuestro Whatsapp)</h5>
        <br>
        <div class="contVolver">
            <img class="volver1" src="images/flecha_inicio.jpg" alt="Foto de flecha para volver" title="Ir al Inicio de esta Página">
            <a class="volver2" href="home"><img src="images/flecha_atras.jpg" alt="Foto de flecha para volver" title="Volver a la Página Principal"></a>
            <img class="lampara" src="images/lampara_off.png" alt="Foto de una lámpara apagada" title="Cambiar a Modo Claro">
        </div>
    </footer>
    <script src="js/prender.js"></script>
    <script src="js/principio.js"></script>
</body>
</html>