<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta base="<?=BASE_URL?>" href="<?=BASE_URL?>">
    <base href="<?=BASE_URL?>">
    <title><?=$pagina?></title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1><?=$titulo?></h1>
        <h3><a id="principio_de_pagina">Usuario:<?=$GLOBALS['usuario']?></a></h3>
    </header> 
    <main>
