<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta base="<?=BASE_URL?>" href="<?=BASE_URL?>">
    <base href="<?=BASE_URL?>">
    <title><?=$pagina?></title>
    <link rel="stylesheet" href="css/mensaje.css">
</head>

<body>
     
    <div class="contCaja">
        <div class="cajaMensaje">
                <h2><?=$titulo?></h2>
                <h3><?=$mensaje?></h3>
                <h3><a href="<?=$volver?>" title="Volver a la página de Inicio" >Aceptar</a></h3>
        </div>
    </div>

</body>

</html>