<?php require_once "templates/header.phtml" ?>

        <article>
            <h3>Metas</h3>
            <h4>A nivel Front End</h4>
            <ul>
                <li>Que sea intuitivo para los Usuarios</li>
                <li>Que escale en el posicionamiento WEB</li>
                <li>Que resulte fácil de compartir</li>
                <li>Que mejore la estética en general</li>
            </ul>
            <h4>A nivel Back End</h4>
            <ul>
                <li>Programación Server-Side</li>
                <li>Encapsular comportamiento</li>
                <li>Programación Orientada a Objetos</li>
                <li>Realizar una Aplicación WEB dinámica</li>
            </ul>
        </article>
        <aside>
            <h3>Disculpe</h3>
            <ul>
                <li>Estamos trabajando en esta página</li>
            <figure>
                <img src="images/alto.jpeg" alt="Foto del logo de Exactas">
            </figure>
        </aside>

<?php require_once "templates/footer.phtml" ?>