<?php require "templates/header.phtml" ?>

        <article>
            <h3>Error 404 Page Not Found</h3>
            <h4>Pasos a seguir...</h4>
            <ul>
                <li>Desestime esta Página</li>
                <li>Vuelva atrás desde su Navegador</li>
                <li>Presione Atrás hasta volver a nuestro sitio</li>
                <li>Comience nuevamente utilzando el Menú</li>
            </ul>
        </article>
        <aside>
            <h3>Disculpe</h3>
            <ul>
                <li>No hemos encontrado la Página solicitada</li>
            <figure>
                <img src="images/page404.jpeg" alt="Foto de Error 404 Page Not Found">
            </figure>
        </aside>

<?php require_once "templates/footer.phtml" ?>