<?php require_once "templates/header.phtml" ?>

        <article>
            <h3>Mostrando <?=$count?> Alumnos</h3>
            <ul>
            <?php foreach($alumnos as $alumno): ?>
                <li>
                    | <a href="alumno/<?=$alumno->id_alumno?>" title="Ver la Ficha del Alumno: <?=$alumno->nombre?>" >Ver</a>
                    <?php if ( $GLOBALS['usuario'] == "Administrador" ) { ?>
                        | <a href="alumno/<?=$alumno->id_alumno?>" title="Modificar los Datos de: <?=$alumno->nombre?>" >Modificar</a>
                        | <a href="eliminar/<?=$alumno->id_alumno?>" title="Borrar al Alumno: <?=$alumno->nombre?>" >Borrar</a>
                    <?php } ?>    
                    | <b><?=$alumno->nombre?></b>
                </li>
            <?php endforeach ?>
            </ul>
        </article>
        <aside>
            <?php if ( $GLOBALS['usuario'] == "Administrador" ) { ?>
                <h4> Para agregar un nuevo Alumno... </h4>
                <h4> Complete el Formulario </h4>         
                <form action="agregar" method="POST">
                    <label for="Nombre">Nombre:</label>
                    <input type="text" name="Nombre" placeholder="Ingrese nombre y apellido..." value="" required/>
                    <label for="Fecha">Fecha de Nacimiento:</label>
                    <input type="date" name="Fecha" value="2000-06-15" min="1924-10-22" max="2024-10-22">
                    <label for="Peso">Peso:</label>
                    <input type="text" name="Peso" value="0.00" >
                    <label for="Altura">Altura:</label>
                    <input type="text" name="Altura" value="0.00" >
                    
                    <label for="Rutina">Rutina de Ejercicios N°:</label>
                            <select name="Rutina" >
                            <option value="1" selected>1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>                  
                            </select>
                            </label>
                    </div>
                    
                    <br>
                    <button type="submit">Aceptar</button>
                </form>
            <?php } else { ?>
                <h3>Nota:</h3>
                <ul>
                    <li>Puede acceder a ver la Ficha del Alumno</li>
                    <li>Presione en VER para lograrlo</li>
                </ul>
            <?php } ?>
        </aside>

<?php require_once "templates/footer.phtml" ?>