<?php require "templates/header.phtml" ?>

        <article>
            <h3>Mostrando <?=$cantidad?> Alumnos</h3>
            <ul>
            <?php foreach($alumnos as $alumno): ?>
                <li>
                    | <a href="alumno/<?=$alumno->id_alumno?>" title="Ver la Ficha del Alumno: <?=$alumno->nombreYapellido?>" >Ver</a>
                    <?php if (isset($_SESSION['ID_USUARIO'])) { ?>
                        | <a href="modificar/<?=$alumno->id_alumno?>" title="Modificar los Datos de: <?=$alumno->nombreYapellido?>" >Modificar</a>
                        | <a href="eliminar/<?=$alumno->id_alumno?>" title="Borrar al Alumno: <?=$alumno->nombreYapellido?>" >Borrar</a>
                    <?php } ?> 
                    <?php $alumno->nombreYapellido = substr($alumno->nombreYapellido,0,25) ?>   
                    | <b><?=$alumno->nombreYapellido?></b>
                </li>
            <?php endforeach ?>
            </ul>
        </article>
        <aside>
        <?php if (isset($_SESSION['ID_USUARIO'])) { ?>
                <h4> Para agregar un nuevo Alumno... </h4>
                <h4> Complete el Formulario </h4>         
                <form action="agregar" method="POST">
                    <label for="Nombre">Nombre:</label>
                    <input type="text" name="Nombre" placeholder="Ingrese nombre y apellido..." value="" required/>
                    <label for="Fecha">Fecha de Nacimiento:</label>
                    <input type="date" name="Fecha" value="2000-06-15" min="1924-10-22" max="2024-10-22">
                    <label for="Peso">Peso:</label>
                    <input type="text" name="Peso" value="0.00" >
                    <label for="Altura">Altura:</label>
                    <input type="text" name="Altura" value="0.00" >
                    <label for="Rutina">Rutina de Ejercicios:</label>
                        <select name="Rutina" >
                            <?php foreach($rutinas as $rutina): ?>
                                <option value="<?=$rutina->id_rutina?>"><?=$rutina->nombre?></option>
                            <?php endforeach ?>  
                        </select>
                    </label>
                    <br>
                    <button type="submit">Aceptar</button>
                </form>
            <?php } else { ?>
                <h3>Nota:</h3>
                <ul>
                    <li>Puede acceder a ver la Ficha del Alumno</li>
                    <li>Presione en VER para lograrlo</li>
                </ul>
            <?php } ?>
        </aside>

<?php require_once "templates/footer.phtml" ?>